# Generated by Django 5.2.5 on 2025-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_media_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
