# Generated by Django 5.2.6 on 2025-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='available_qualities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='hls_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='is_stream_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='stream_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('ready', 'Listo'), ('failed', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
