# Generated by Django 5.2.6 on 2025-09-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_media_available_qualities_media_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('current_media_id', models.IntegerField(blank=True, null=True)),
                ('current_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('playlist_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playlist_state',
            },
        ),
    ]
