# Generated by Django 5.2 on 2025-09-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_playlist_state'),
    ]

    operations = [
        # SQLite no soporta DROP COLUMN IF EXISTS, así que omitimos esta operación para compatibilidad local
    ]
