# Generated by Django 5.2.6 on 2025-10-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20250926_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playliststate',
            name='current_index',
        ),
    ]
