# Generated by Django 5.2 on 2025-10-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_add_task_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='proyectos/archivos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='videos.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_proyecto_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Proyecto',
                'verbose_name_plural': 'Archivos de Proyecto',
                'db_table': 'archivo_proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tareas/archivos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_tarea_subidos', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='videos.tarea')),
            ],
            options={
                'verbose_name': 'Archivo de Tarea',
                'verbose_name_plural': 'Archivos de Tarea',
                'db_table': 'archivo_tarea',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_proyecto', to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='videos.comentarioproyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='videos.proyecto')),
            ],
            options={
                'verbose_name': 'Comentario de Proyecto',
                'verbose_name_plural': 'Comentarios de Proyecto',
                'db_table': 'comentario_proyecto',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='videos.comentariotarea')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='videos.tarea')),
            ],
            options={
                'verbose_name': 'Comentario de Tarea',
                'verbose_name_plural': 'Comentarios de Tarea',
                'db_table': 'comentario_tarea',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comentarios/archivos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_comentario_subidos', to=settings.AUTH_USER_MODEL)),
                ('comentario_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='videos.comentarioproyecto')),
                ('comentario_tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='videos.comentariotarea')),
            ],
            options={
                'verbose_name': 'Archivo de Comentario',
                'verbose_name_plural': 'Archivos de Comentario',
                'db_table': 'archivo_comentario',
                'ordering': ['-created_at'],
            },
        ),
    ]
