# Generated by Django 5.2 on 2025-10-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_playliststate_current_index_archivoproyecto_and_more'),
    ]

    operations = [
    ]
