# Generated by Django 5.2 on 2025-10-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20251006_0929'),
    ]

    operations = [
    ]
