# Generated by Django 5.2 on 2025-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20251008_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='configuracion_notificaciones',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tema_preferido',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='zona_horaria',
        ),
        migrations.RemoveField(
            model_name='playliststate',
            name='current_index',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellidos',
            field=models.CharField(default='Pendiente', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='area_trabajo',
            field=models.CharField(choices=[('informatica', 'Informática/IT'), ('contabilidad', 'Contabilidad'), ('administracion', 'Administración'), ('gerencia', 'Gerencia'), ('mercadotecnia', 'Mercadotecnia'), ('creditos', 'Créditos'), ('recursos_humanos', 'Recursos Humanos'), ('legal', 'Legal'), ('auditoria', 'Auditoría'), ('secretaria', 'Secretaría'), ('otro', 'Otro')], default='Usuario', max_length=50, verbose_name='Área de Trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo/Posición'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombres',
            field=models.CharField(default='otro', max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono_extension',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono/Extensión'),
        ),
    ]
