# Generated by Django 5.2 on 2025-10-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0011_remove_perfilusuario_bio_and_more'),
    ]

    operations = [
        # Asegurar que PerfilUsuario tiene todos los campos necesarios
        migrations.AddField(
            model_name='perfilusuario',
            name='nombres',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellidos',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='area_trabajo',
            field=models.CharField(
                choices=[
                    ('mercadeo', 'Mercadeo y Comunicación'),
                    ('creditos', 'Créditos'),
                    ('operaciones', 'Operaciones'),
                    ('administracion', 'Administración'),
                    ('rrhh', 'Recursos Humanos'),
                    ('it', 'Tecnología'),
                    ('gerencia', 'Gerencia'),
                    ('auditoria', 'Auditoría'),
                    ('legal', 'Legal'),
                    ('otros', 'Otros')
                ],
                default='otros',
                max_length=50,
                verbose_name='Área de Trabajo'
            ),
        ),
    ]
