# Generated by Django 5.2.6 on 2025-10-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_add_perfil_usuario_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='area_trabajo',
            field=models.CharField(choices=[('informatica', 'Informática/IT'), ('contabilidad', 'Contabilidad'), ('administracion', 'Administración'), ('gerencia', 'Gerencia'), ('mercadotecnia', 'Mercadotecnia'), ('creditos', 'Créditos'), ('recursos_humanos', 'Recursos Humanos'), ('legal', 'Legal'), ('auditoria', 'Auditoría'), ('secretaria', 'Secretaría'), ('otro', 'Otro')], max_length=50, verbose_name='Área de Trabajo'),
        ),
    ]
