# Generated by Django 5.2 on 2025-10-31 22:40

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_perfilusuario_area_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=videos.models.media_upload_to),
        ),
    ]
